apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: manuela-demo-messaging-
  generation: 1
  name: manuela-demo-messaging
  namespace: manuela-demo-messaging
spec:
  targetNamespaces:
  - manuela-demo-messaging