apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aionedge
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lavlas/manuela-gitops.git
    targetRevision: aionedge
    path: deployment/execenv-aionedge
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status
